version: "3.7"
services:
  yii-demo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-develop
      args:
        HOST_USER_ID: ${HOST_USER_ID:-1000}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
    ports:
      - ${SERVER_PORT:-8000}:8080
    volumes:
      - ./:/app
    env_file:
      - .app.env
