version: "3.7"
services:
  yii-demo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        HOST_USER_ID: ${HOST_USER_ID:-1000}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
    image: image-develop
    ports:
      - ${SERVER_PORT:-8000}:8080
    volumes:
      - ./:/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    command: /bin/sh -c 'composer install && php yii serve 0.0.0.0:8080'
