version: "3.7"
services:
  yii-demo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
      args:
        HOST_USER_ID: ${HOST_USER_ID:-1000}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
    ports:
      - ${SERVER_PORT:-8080}:8080
    volumes:
      - ./:/app
    command: /bin/sh -c 'tail -f /dev/null'
