# syntax=docker/dockerfile:1
FROM alpine AS yii-demo-develop

ENV GIT_WORK_TREE=/app GIT_DIR=/app/.git

RUN apk add\
 zsh\
 git\
 composer\
 php81\
 php81-dom\
 php81-xml\
 php81-xmlwriter\
 php81-curl\
 php81-iconv\
 php81-mbstring\
 php81-openssl\
 php81-zip\
 php81-tokenizer\
 php81-session\
 php81-gd\
 php81-ctype\
 php81-pdo\
 php81-pdo_pgsql\
 php81-pdo_mysql\
 php81-pdo_sqlite\
 php81-pecl-imagick\
 php81-intl\
 php81-fileinfo\
 php81-pecl-memcache

WORKDIR /app

COPY ./docker/php.ini /etc/php81/php.ini

ARG HOST_USER_ID=1000
ARG HOST_GROUP_ID=1000
ARG USER_NAME=user

# create user if not exist
RUN addgroup -S ${HOST_GROUP_ID} || true

RUN adduser --disabled-password --gecos "" --ingroup "${HOST_GROUP_ID}"\
 --uid "${HOST_USER_ID}" "${USER_NAME}" || true

# act as non-root user inside container (1000:1000 by default)
USER ${HOST_USER_ID}:${HOST_GROUP_ID}

# create empty config in order to avoid initial prompt
RUN touch ~/.zshrc

CMD composer install && php yii serve 0.0.0.0:8080
