# syntax=docker/dockerfile:1
# image for production
FROM alpine AS yii-demo-production

RUN apk add\
 nginx\
 composer\
 php81-fpm\
 php81\
 php81-dom\
 php81-xml\
 php81-xmlwriter\
 php81-curl\
 php81-iconv\
 php81-mbstring\
 php81-openssl\
 php81-zip\
 php81-tokenizer\
 php81-session\
 php81-gd\
 php81-ctype\
 php81-pdo\
 php81-pdo_pgsql\
 php81-pdo_mysql\
 php81-pdo_sqlite\
 php81-pecl-imagick\
 php81-intl\
 php81-fileinfo\
 php81-pecl-memcache

WORKDIR /app

COPY ./docker/php.ini /etc/php81/php.ini
COPY ./docker/nginx/yii-demo.conf /etc/nginx/http.d/yii-demo.conf
COPY ./docker/php-fpm/www.conf /etc/php81/php-fpm.d/www.conf
COPY ./docker/startup.sh /startup.sh
RUN chmod +x /startup.sh
RUN rm /etc/nginx/http.d/default.conf

COPY ./ /app
RUN composer install
RUN chown -R nginx:nginx ./

CMD ["/startup.sh"]
